/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/yJi2Na4NbyE
 */

import { Button } from '@/components/ui/button'
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from '@/components/ui/table'
import { PopoverTrigger, PopoverContent, Popover } from '@/components/ui/popover'

export function Documents() {
  return (
    <main className='flex flex-1 flex-col gap-4 p-4 md:gap-8 md:p-6'>
      <div className='flex items-center'>
        <h1 className='font-semibold text-lg md:text-2xl'>Documents</h1>
        <Button className='ml-auto' size='sm'>
          Upload
        </Button>
        <Button className='ml-2' size='sm' variant='outline'>
          New folder
        </Button>
        <Button className='ml-2' size='sm' variant='outline'>
          Delete
        </Button>
      </div>
      <div className='border shadow-sm rounded-lg'>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead className='w-[200px]'>Name</TableHead>
              <TableHead>Type</TableHead>
              <TableHead>Size</TableHead>
              <TableHead>Date</TableHead>
              <TableHead className='w-[100px]'>Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            <TableRow>
              <TableCell className='font-medium'>Q4-financial-report.pdf</TableCell>
              <TableCell>PDF</TableCell>
              <TableCell>2.3MB</TableCell>
              <TableCell>2023-10-12</TableCell>
              <TableCell>
                <Popover>
                  <PopoverTrigger asChild>
                    <Button className='mx-1' size='icon' variant='ghost'>
                      <MoreHorizontalIcon className='w-4 h-4' />
                      <span className='sr-only'>More</span>
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent className='flex items-start p-0 gap-1.5 w-24'>
                    <div />
                    <div>
                      <div className='flex items-center gap-2.5'>
                        <FileEditIcon className='w-4 h-4' />
                        Edit
                      </div>
                      <div className='flex items-center gap-2.5'>
                        <TrashIcon className='w-4 h-4' />
                        Delete
                      </div>
                    </div>
                  </PopoverContent>
                </Popover>
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className='font-medium'>Wireframes.zip</TableCell>
              <TableCell>ZIP</TableCell>
              <TableCell>5.1MB</TableCell>
              <TableCell>2023-09-28</TableCell>
              <TableCell>
                <Popover>
                  <PopoverTrigger asChild>
                    <Button className='mx-1' size='icon' variant='ghost'>
                      <MoreHorizontalIcon className='w-4 h-4' />
                      <span className='sr-only'>More</span>
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent className='flex items-start p-0 gap-1.5 w-24'>
                    <div />
                    <div>
                      <div className='flex items-center gap-2.5'>
                        <FileEditIcon className='w-4 h-4' />
                        Edit
                      </div>
                      <div className='flex items-center gap-2.5'>
                        <TrashIcon className='w-4 h-4' />
                        Delete
                      </div>
                    </div>
                  </PopoverContent>
                </Popover>
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className='font-medium'>Budget-spreadsheet.xlsx</TableCell>
              <TableCell>Excel</TableCell>
              <TableCell>1.2MB</TableCell>
              <TableCell>2023-09-15</TableCell>
              <TableCell>
                <Popover>
                  <PopoverTrigger asChild>
                    <Button className='mx-1' size='icon' variant='ghost'>
                      <MoreHorizontalIcon className='w-4 h-4' />
                      <span className='sr-only'>More</span>
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent className='flex items-start p-0 gap-1.5 w-24'>
                    <div />
                    <div>
                      <div className='flex items-center gap-2.5'>
                        <FileEditIcon className='w-4 h-4' />
                        Edit
                      </div>
                      <div className='flex items-center gap-2.5'>
                        <TrashIcon className='w-4 h-4' />
                        Delete
                      </div>
                    </div>
                  </PopoverContent>
                </Popover>
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className='font-medium'>Project-presentation.pptx</TableCell>
              <TableCell>PowerPoint</TableCell>
              <TableCell>3.7MB</TableCell>
              <TableCell>2023-08-29</TableCell>
              <TableCell>
                <Popover>
                  <PopoverTrigger asChild>
                    <Button className='mx-1' size='icon' variant='ghost'>
                      <MoreHorizontalIcon className='w-4 h-4' />
                      <span className='sr-only'>More</span>
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent className='flex items-start p-0 gap-1.5 w-24'>
                    <div />
                    <div>
                      <div className='flex items-center gap-2.5'>
                        <FileEditIcon className='w-4 h-4' />
                        Edit
                      </div>
                      <div className='flex items-center gap-2.5'>
                        <TrashIcon className='w-4 h-4' />
                        Delete
                      </div>
                    </div>
                  </PopoverContent>
                </Popover>
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className='font-medium'>Team-meeting-notes.docx</TableCell>
              <TableCell>Word</TableCell>
              <TableCell>1.8MB</TableCell>
              <TableCell>2023-08-15</TableCell>
              <TableCell>
                <Popover>
                  <PopoverTrigger asChild>
                    <Button className='mx-1' size='icon' variant='ghost'>
                      <MoreHorizontalIcon className='w-4 h-4' />
                      <span className='sr-only'>More</span>
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent className='flex items-start p-0 gap-1.5 w-24'>
                    <div />
                    <div>
                      <div className='flex items-center gap-2.5'>
                        <FileEditIcon className='w-4 h-4' />
                        Edit
                      </div>
                      <div className='flex items-center gap-2.5'>
                        <TrashIcon className='w-4 h-4' />
                        Delete
                      </div>
                    </div>
                  </PopoverContent>
                </Popover>
              </TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </div>
    </main>
  )
}

function MoreHorizontalIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'
    >
      <circle cx='12' cy='12' r='1' />
      <circle cx='19' cy='12' r='1' />
      <circle cx='5' cy='12' r='1' />
    </svg>
  )
}

function FileEditIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'
    >
      <path d='M4 13.5V4a2 2 0 0 1 2-2h8.5L20 7.5V20a2 2 0 0 1-2 2h-5.5' />
      <polyline points='14 2 14 8 20 8' />
      <path d='M10.42 12.61a2.1 2.1 0 1 1 2.97 2.97L7.95 21 4 22l.99-3.95 5.43-5.44Z' />
    </svg>
  )
}

function TrashIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'
    >
      <path d='M3 6h18' />
      <path d='M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6' />
      <path d='M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2' />
    </svg>
  )
}
