/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/yJi2Na4NbyE
 */

import { Button } from '@/components/ui/button'
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from '@/components/ui/table'
import { PopoverTrigger, PopoverContent, Popover } from '@/components/ui/popover'

export function Documents() {
  return (
    <main className='flex flex-1 flex-col gap-4 p-4 md:gap-8 md:p-6'>
      <div className='flex items-center'>
        <h1 className='font-semibold text-lg md:text-2xl'>Documents</h1>
        <Button className='ml-auto' size='sm'>
          Upload
        </Button>
        <Button className='ml-2' size='sm' variant='outline'>
          New folder
        </Button>
        <Button className='ml-2' size='sm' variant='outline'>
          Delete
        </Button>
      </div>
      <div className='border shadow-sm rounded-lg'>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead className='w-[200px]'>Name</TableHead>
              <TableHead>Type</TableHead>
              <TableHead>Size</TableHead>
              <TableHead>Date</TableHead>
              <TableHead className='w-[100px]'>Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            <TableRow>
              <TableCell className='font-medium'>Q4-financial-report.pdf</TableCell>
              <TableCell>PDF</TableCell>
              <TableCell>2.3MB</TableCell>
              <TableCell>2023-10-12</TableCell>
              <TableCell>
                <Popover>
                  <PopoverTrigger asChild>
                    <Button className='mx-1' size='icon' variant='ghost'>
                      <MoreHorizontalIcon className='w-4 h-4' />
                      <span className='sr-only'>More</span>
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent className='flex items-start p-0 gap-1.5 w-24'>
                    <div />
                    <div>
                      <div className='flex items-center gap-2.5'>
                        <FileEditIcon className='w-4 h-4' />
                        Edit
                      </div>
                      <div className='flex items-center gap-2.5'>
                        <TrashIcon className='w-4 h-4' />
                        Delete
                      </div>
                    </div>
                  </PopoverContent>
                </Popover>
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className='font-medium'>Wireframes.zip</TableCell>
              <TableCell>ZIP</TableCell>
              <TableCell>5.1MB</TableCell>
              <TableCell>2023-09-28</TableCell>
              <TableCell>
                <Popover>
                  <PopoverTrigger asChild>
                    <Button className='mx-1' size='icon' variant='ghost'>
                      <MoreHorizontalIcon className='w-4 h-4' />
                      <span className='sr-only'>More</span>
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent className='flex items-start p-0 gap-1.5 w-24'>
                    <div />
                    <div>
                      <div className='flex items-center gap-2.5'>
                        <FileEditIcon className='w-4 h-4' />
                        Edit
                      </div>
                      <div className='flex items-center gap-2.5'>
                        <TrashIcon className='w-4 h-4' />
                        Delete
                      </div>
                    </div>
                  </PopoverContent>
                </Popover>
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className='font-medium'>Budget-spreadsheet.xlsx</TableCell>
              <TableCell>Excel</TableCell>
              <TableCell>1.2MB</TableCell>
              <TableCell>2023-09-15</TableCell>
              <TableCell>
                <Popover>
                  <PopoverTrigger asChild>
                    <Button className='mx-1' size='icon' variant='ghost'>
                      <MoreHorizontalIcon className='w-4 h-4' />
                      <span className='sr-only'>More</span>
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent className='flex items-start p-0 gap-1.5 w-24'>
                    <div />
                    <div>
                      <div className='flex items-center gap-2.5'>
                        <FileEditIcon className='w-4 h-4' />
                        Edit
                      </div>
                      <div className='flex items-center gap-2.5'>
                        <TrashIcon className='w-4 h-4' />
                        Delete
                      </div>
                    </div>
                  </PopoverContent>
                </Popover>
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className='font-medium'>Project-presentation.pptx</TableCell>
              <TableCell>PowerPoint</TableCell>
              <TableCell>3.7MB</TableCell>
              <TableCell>2023-08-29</TableCell>
              <TableCell>
                <Popover>
                  <PopoverTrigger asChild>
                    <Button className='mx-1' size='icon' variant='ghost'>
                      <MoreHorizontalIcon className='w-4 h-4' />
                      <span className='sr-only'>More</span>
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent className='flex items-start p-0 gap-1.5 w-24'>
                    <div />
                    <div>
                      <div className='flex items-center gap-2.5'>
                        <FileEditIcon className='w-4 h-4' />
                        Edit
                      </div>
                      <div className='flex items-center gap-2.5'>
                        <TrashIcon className='w-4 h-4' />
                        Delete
                      </div>
                    </div>
                  </PopoverContent>
                </Popover>
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className='font-medium'>Team-meeting-notes.docx</TableCell>
              <TableCell>Word</TableCell>
              <TableCell>1.8MB</TableCell>
              <TableCell>2023-08-15</TableCell>
              <TableCell>
                <Popover>
                  <PopoverTrigger asChild>
                    <Button className='mx-1' size='icon' variant='ghost'>
                      <MoreHorizontalIcon className='w-4 h-4' />
                      <span className='sr-only'>More</span>
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent className='flex items-start p-0 gap-1.5 w-24'>
                    <div />
                    <div>
                      <div className='flex items-center gap-2.5'>
                        <FileEditIcon className='w-4 h-4' />
                        Edit
                      </div>
                      <div className='flex items-center gap-2.5'>
                        <TrashIcon className='w-4 h-4' />
                        Delete
                      </div>
                    </div>
                  </PopoverContent>
                </Popover>
              </TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </div>
    </main>
  )
}

function Package2Icon(props) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'
    >
      <path d='M3 9h18v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9Z' />
      <path d='m3 9 2.45-4.9A2 2 0 0 1 7.24 3h9.52a2 2 0 0 1 1.8 1.1L21 9' />
      <path d='M12 3v6' />
    </svg>
  )
}

function BellIcon(props) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'
    >
      <path d='M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9' />
      <path d='M10.3 21a1.94 1.94 0 0 0 3.4 0' />
    </svg>
  )
}

function HomeIcon(props) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'
    >
      <path d='m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z' />
      <polyline points='9 22 9 12 15 12 15 22' />
    </svg>
  )
}

function FolderIcon(props) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'
    >
      <path d='M4 20h16a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.93a2 2 0 0 1-1.66-.9l-.82-1.2A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13c0 1.1.9 2 2 2Z' />
    </svg>
  )
}

function FileIcon(props) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'
    >
      <path d='M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z' />
      <polyline points='14 2 14 8 20 8' />
    </svg>
  )
}

function UsersIcon(props) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'
    >
      <path d='M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2' />
      <circle cx='9' cy='7' r='4' />
      <path d='M22 21v-2a4 4 0 0 0-3-3.87' />
      <path d='M16 3.13a4 4 0 0 1 0 7.75' />
    </svg>
  )
}

function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'
    >
      <circle cx='11' cy='11' r='8' />
      <path d='m21 21-4.3-4.3' />
    </svg>
  )
}

function MoreHorizontalIcon(props) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'
    >
      <circle cx='12' cy='12' r='1' />
      <circle cx='19' cy='12' r='1' />
      <circle cx='5' cy='12' r='1' />
    </svg>
  )
}

function FileEditIcon(props) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'
    >
      <path d='M4 13.5V4a2 2 0 0 1 2-2h8.5L20 7.5V20a2 2 0 0 1-2 2h-5.5' />
      <polyline points='14 2 14 8 20 8' />
      <path d='M10.42 12.61a2.1 2.1 0 1 1 2.97 2.97L7.95 21 4 22l.99-3.95 5.43-5.44Z' />
    </svg>
  )
}

function TrashIcon(props) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'
    >
      <path d='M3 6h18' />
      <path d='M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6' />
      <path d='M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2' />
    </svg>
  )
}
